classdef test_make_difference_plot < matlab.unittest.TestCase  %#ok<*PROP>

    % Tests the make_difference_plot function with the following cases:
    %     TBD

    properties
        fig_hand,
        description,
        time_one,
        data_one,
        time_two,
        data_two,
        name_one,
        name_two,
        elements,
        units,
        time_units,
        start_date,
        rms_xmin,
        rms_xmax,
        disp_xmin,
        disp_xmax,
        make_subplots,
        single_lines,
        color_map,
        use_mean,
        plot_zero,
        show_rms,
        legend_loc,
        show_extra,
        second_units,
        legend_scale,
        ylabel,
        data_as_rows,
        extra_plotter,
        tolerance,
        use_zoh,
        label_vert_lines,
        fig_visible,
    end

    methods (TestMethodSetup)
        function initialize(self)
            self.description      = 'example';
            self.time_one         = 0:10;
            self.data_one         = 1e-6 * rand(2, 11);
            self.time_two         = 2:12;
            self.data_two         = self.data_one(:, [3, 4, 5, 6, 7, 8, 9, 10, 11, 1, 2]) - 1e-6;
            self.name_one         = 'test1';
            self.name_two         = 'test2';
            self.elements         = ["x", "y"];
            self.units            = 'rad';
            self.time_units       = 'sec';
            self.start_date       = char(datetime('now'));
            self.rms_xmin         = 0;
            self.rms_xmax         = 10;
            self.disp_xmin        = -2;
            self.disp_xmax        = inf;
            self.make_subplots    = true;
            self.single_lines     = false;
            color_lists           = matspace.plotting.colors.get_color_lists();
            self.color_map         = color_lists.dbl_comp;
            self.use_mean         = false;
            self.plot_zero        = false;
            self.show_rms         = true;
            self.legend_loc       = 'best';
            self.show_extra       = true;
            self.second_units     = 'micro';
            self.ylabel           = '';
            self.data_as_rows     = true;
            self.tolerance        = 0;
            self.use_zoh          = false;
            self.label_vert_lines = true;
            self.fig_visible      = false;
        end
    end

    methods (TestMethodTeardown)
        function closeFigure(self)
            close(self.fig_hand);
        end
    end

    methods (Test)
        function test_nominal(self)
            self.fig_hand = matspace.plotting.make_difference_plot(...
                self.description, ...
                self.time_one, ...
                self.data_one, ...
                self.time_two, ...
                self.data_two, ...
                NameOne=self.name_one, ...
                NameTwo=self.name_two, ...
                Elements=self.elements, ...
                Units=self.units, ...
                TimeUnits=self.time_units, ...
                StartDate=self.start_date, ...
                RmsXmin=self.rms_xmin, ...
                RmsXmax=self.rms_xmax, ...
                DispXmin=self.disp_xmin, ...
                DispXmax=self.disp_xmax, ...
                MakeSubplots=self.make_subplots, ...
                SingleLines=self.single_lines, ...
                ColorMap=self.color_map, ...
                UseMean=self.use_mean, ...
                PlotZero=self.plot_zero, ...
                ShowRms=self.show_rms, ...
                LegendLoc=self.legend_loc, ...
                ShowExtra=self.show_extra, ...
                SecondUnits=self.second_units, ...
                YLabel=self.ylabel, ...
                DataAsRows=self.data_as_rows, ...
                Tolerance=self.tolerance, ...
                UseZoh=self.use_zoh, ...
                LabelVertLines=self.label_vert_lines, ...
                FigVisible=self.fig_visible);
            self.verifyNotEmpty(self.fig_hand);
            self.verifyGreaterThanOrEqual(length(self.fig_hand), 1);
        end

        function test_no_subplots(self)
            self.make_subplots = false;
            [self.fig_hand, err] = matspace.plotting.make_difference_plot(...
                self.description, ...
                self.time_one, ...
                self.data_one, ...
                self.time_two, ...
                self.data_two, ...
                NameOne=self.name_one, ...
                NameTwo=self.name_two, ...
                Elements=self.elements, ...
                Units=self.units, ...
                TimeUnits=self.time_units, ...
                StartDate=self.start_date, ...
                RmsXmin=self.rms_xmin, ...
                RmsXmax=self.rms_xmax, ...
                DispXmin=self.disp_xmin, ...
                DispXmax=self.disp_xmax, ...
                MakeSubplots=self.make_subplots, ...
                SingleLines=self.single_lines, ...
                ColorMap=self.color_map, ...
                UseMean=self.use_mean, ...
                PlotZero=self.plot_zero, ...
                ShowRms=self.show_rms, ...
                LegendLoc=self.legend_loc, ...
                ShowExtra=self.show_extra, ...
                SecondUnits=self.second_units, ...
                YLabel=self.ylabel, ...
                DataAsRows=self.data_as_rows, ...
                Tolerance=self.tolerance, ...
                UseZoh=self.use_zoh, ...
                LabelVertLines=self.label_vert_lines, ...
                FigVisible=self.fig_visible);
            self.verifyNotEmpty(self.fig_hand);
            self.verifyGreaterThanOrEqual(length(self.fig_hand), 1);
        end

        function test_no_start_date(self)
            self.start_date = '';
            [self.fig_hand, err] = matspace.plotting.make_difference_plot(...
                self.description, ...
                self.time_one, ...
                self.data_one, ...
                self.time_two, ...
                self.data_two, ...
                NameOne=self.name_one, ...
                NameTwo=self.name_two, ...
                Elements=self.elements, ...
                Units=self.units, ...
                TimeUnits=self.time_units, ...
                StartDate=self.start_date, ...
                RmsXmin=self.rms_xmin, ...
                RmsXmax=self.rms_xmax, ...
                DispXmin=self.disp_xmin, ...
                DispXmax=self.disp_xmax, ...
                MakeSubplots=self.make_subplots, ...
                SingleLines=self.single_lines, ...
                ColorMap=self.color_map, ...
                UseMean=self.use_mean, ...
                PlotZero=self.plot_zero, ...
                ShowRms=self.show_rms, ...
                LegendLoc=self.legend_loc, ...
                ShowExtra=self.show_extra, ...
                SecondUnits=self.second_units, ...
                YLabel=self.ylabel, ...
                DataAsRows=self.data_as_rows, ...
                Tolerance=self.tolerance, ...
                UseZoh=self.use_zoh, ...
                LabelVertLines=self.label_vert_lines, ...
                FigVisible=self.fig_visible);
            self.verifyNotEmpty(self.fig_hand);
            self.verifyGreaterThanOrEqual(length(self.fig_hand), 1);
        end

        function test_only_data_one(self)
            self.data_two(:) = nan;
            self.name_two = '';
            [self.fig_hand, err] = matspace.plotting.make_difference_plot(...
                self.description, ...
                self.time_one, ...
                self.data_one, ...
                self.time_two, ...
                self.data_two, ...
                NameOne=self.name_one, ...
                NameTwo=self.name_two, ...
                Elements=self.elements, ...
                Units=self.units, ...
                TimeUnits=self.time_units, ...
                StartDate=self.start_date, ...
                RmsXmin=self.rms_xmin, ...
                RmsXmax=self.rms_xmax, ...
                DispXmin=self.disp_xmin, ...
                DispXmax=self.disp_xmax, ...
                MakeSubplots=self.make_subplots, ...
                SingleLines=self.single_lines, ...
                ColorMap=self.color_map, ...
                UseMean=self.use_mean, ...
                PlotZero=self.plot_zero, ...
                ShowRms=self.show_rms, ...
                LegendLoc=self.legend_loc, ...
                ShowExtra=self.show_extra, ...
                SecondUnits=self.second_units, ...
                YLabel=self.ylabel, ...
                DataAsRows=self.data_as_rows, ...
                Tolerance=self.tolerance, ...
                UseZoh=self.use_zoh, ...
                LabelVertLines=self.label_vert_lines, ...
                FigVisible=self.fig_visible);
            self.verifyNotEmpty(self.fig_hand);
            self.verifyGreaterThanOrEqual(length(self.fig_hand), 1);
            self.verifyTrue(all(isnan(err.diff)));
        end

        function test_only_data_two(self)
            self.data_one = [];
            self.name_one = '';
            [self.fig_hand, err] = matspace.plotting.make_difference_plot(...
                self.description, ...
                self.time_one, ...
                self.data_one, ...
                self.time_two, ...
                self.data_two, ...
                NameOne=self.name_one, ...
                NameTwo=self.name_two, ...
                Elements=self.elements, ...
                Units=self.units, ...
                TimeUnits=self.time_units, ...
                StartDate=self.start_date, ...
                RmsXmin=self.rms_xmin, ...
                RmsXmax=self.rms_xmax, ...
                DispXmin=self.disp_xmin, ...
                DispXmax=self.disp_xmax, ...
                MakeSubplots=self.make_subplots, ...
                SingleLines=self.single_lines, ...
                ColorMap=self.color_map, ...
                UseMean=self.use_mean, ...
                PlotZero=self.plot_zero, ...
                ShowRms=self.show_rms, ...
                LegendLoc=self.legend_loc, ...
                ShowExtra=self.show_extra, ...
                SecondUnits=self.second_units, ...
                YLabel=self.ylabel, ...
                DataAsRows=self.data_as_rows, ...
                Tolerance=self.tolerance, ...
                UseZoh=self.use_zoh, ...
                LabelVertLines=self.label_vert_lines, ...
                FigVisible=self.fig_visible);
            self.verifyNotEmpty(self.fig_hand);
            self.verifyGreaterThanOrEqual(length(self.fig_hand), 1);
            self.verifyTrue(all(isnan(err.diff)));
        end

        function test_rms_bounds(self)
            self.rms_xmin = 5;
            self.rms_xmax = 7;
            [self.fig_hand, err] = matspace.plotting.make_difference_plot(...
                self.description, ...
                self.time_one, ...
                self.data_one, ...
                self.time_two, ...
                self.data_two, ...
                NameOne=self.name_one, ...
                NameTwo=self.name_two, ...
                Elements=self.elements, ...
                Units=self.units, ...
                TimeUnits=self.time_units, ...
                StartDate=self.start_date, ...
                RmsXmin=self.rms_xmin, ...
                RmsXmax=self.rms_xmax, ...
                DispXmin=self.disp_xmin, ...
                DispXmax=self.disp_xmax, ...
                MakeSubplots=self.make_subplots, ...
                SingleLines=self.single_lines, ...
                ColorMap=self.color_map, ...
                UseMean=self.use_mean, ...
                PlotZero=self.plot_zero, ...
                ShowRms=self.show_rms, ...
                LegendLoc=self.legend_loc, ...
                ShowExtra=self.show_extra, ...
                SecondUnits=self.second_units, ...
                YLabel=self.ylabel, ...
                DataAsRows=self.data_as_rows, ...
                Tolerance=self.tolerance, ...
                UseZoh=self.use_zoh, ...
                LabelVertLines=self.label_vert_lines, ...
                FigVisible=self.fig_visible);
            self.verifyNotEmpty(self.fig_hand);
            self.verifyGreaterThanOrEqual(length(self.fig_hand), 1);
        end

        function test_use_mean(self)
            self.use_mean = true;
            [self.fig_hand, err] = matspace.plotting.make_difference_plot(...
                self.description, ...
                self.time_one, ...
                self.data_one, ...
                self.time_two, ...
                self.data_two, ...
                NameOne=self.name_one, ...
                NameTwo=self.name_two, ...
                Elements=self.elements, ...
                Units=self.units, ...
                TimeUnits=self.time_units, ...
                StartDate=self.start_date, ...
                RmsXmin=self.rms_xmin, ...
                RmsXmax=self.rms_xmax, ...
                DispXmin=self.disp_xmin, ...
                DispXmax=self.disp_xmax, ...
                MakeSubplots=self.make_subplots, ...
                SingleLines=self.single_lines, ...
                ColorMap=self.color_map, ...
                UseMean=self.use_mean, ...
                PlotZero=self.plot_zero, ...
                ShowRms=self.show_rms, ...
                LegendLoc=self.legend_loc, ...
                ShowExtra=self.show_extra, ...
                SecondUnits=self.second_units, ...
                YLabel=self.ylabel, ...
                DataAsRows=self.data_as_rows, ...
                Tolerance=self.tolerance, ...
                UseZoh=self.use_zoh, ...
                LabelVertLines=self.label_vert_lines, ...
                FigVisible=self.fig_visible);
            self.verifyNotEmpty(self.fig_hand);
            self.verifyGreaterThanOrEqual(length(self.fig_hand), 1);
        end

        function test_no_rms_in_legend(self)
            self.show_rms = false;
            [self.fig_hand, err] = matspace.plotting.make_difference_plot(...
                self.description, ...
                self.time_one, ...
                self.data_one, ...
                self.time_two, ...
                self.data_two, ...
                NameOne=self.name_one, ...
                NameTwo=self.name_two, ...
                Elements=self.elements, ...
                Units=self.units, ...
                TimeUnits=self.time_units, ...
                StartDate=self.start_date, ...
                RmsXmin=self.rms_xmin, ...
                RmsXmax=self.rms_xmax, ...
                DispXmin=self.disp_xmin, ...
                DispXmax=self.disp_xmax, ...
                MakeSubplots=self.make_subplots, ...
                SingleLines=self.single_lines, ...
                ColorMap=self.color_map, ...
                UseMean=self.use_mean, ...
                PlotZero=self.plot_zero, ...
                ShowRms=self.show_rms, ...
                LegendLoc=self.legend_loc, ...
                ShowExtra=self.show_extra, ...
                SecondUnits=self.second_units, ...
                YLabel=self.ylabel, ...
                DataAsRows=self.data_as_rows, ...
                Tolerance=self.tolerance, ...
                UseZoh=self.use_zoh, ...
                LabelVertLines=self.label_vert_lines, ...
                FigVisible=self.fig_visible);
            self.verifyNotEmpty(self.fig_hand);
            self.verifyGreaterThanOrEqual(length(self.fig_hand), 1);
        end

        function test_plot_zero(self)
            self.plot_zero = true;
            [self.fig_hand, err] = matspace.plotting.make_difference_plot(...
                self.description, ...
                self.time_one, ...
                self.data_one, ...
                self.time_two, ...
                self.data_two, ...
                NameOne=self.name_one, ...
                NameTwo=self.name_two, ...
                Elements=self.elements, ...
                Units=self.units, ...
                TimeUnits=self.time_units, ...
                StartDate=self.start_date, ...
                RmsXmin=self.rms_xmin, ...
                RmsXmax=self.rms_xmax, ...
                DispXmin=self.disp_xmin, ...
                DispXmax=self.disp_xmax, ...
                MakeSubplots=self.make_subplots, ...
                SingleLines=self.single_lines, ...
                ColorMap=self.color_map, ...
                UseMean=self.use_mean, ...
                PlotZero=self.plot_zero, ...
                ShowRms=self.show_rms, ...
                LegendLoc=self.legend_loc, ...
                ShowExtra=self.show_extra, ...
                SecondUnits=self.second_units, ...
                YLabel=self.ylabel, ...
                DataAsRows=self.data_as_rows, ...
                Tolerance=self.tolerance, ...
                UseZoh=self.use_zoh, ...
                LabelVertLines=self.label_vert_lines, ...
                FigVisible=self.fig_visible);
            self.verifyNotEmpty(self.fig_hand);
            self.verifyGreaterThanOrEqual(length(self.fig_hand), 1);
        end

        function test_disp_bounds(self)
            self.fig_hand = matspace.plotting.make_difference_plot(...
                self.description, ...
                self.time_one, ...
                self.data_one, ...
                self.time_two, ...
                self.data_two, ...
                Elements=self.elements, ...
                Units=self.units, ...
                DispXmin=2, ...
                DispXmax=5, ...
                FigVisible=self.fig_visible);
            self.verifyNotEmpty(self.fig_hand);
            self.verifyGreaterThanOrEqual(length(self.fig_hand), 1);
        end

        function test_no_overlap(self)
            time_one = 0:10;
            time_two = (2:12) + 0.5;
            self.fig_hand = matspace.plotting.make_difference_plot(...
                self.description, ...
                time_one, ...
                self.data_one, ...
                time_two, ...
                self.data_two, ...
                NameOne=self.name_one, ...
                NameTwo=self.name_two, ...
                Elements=self.elements, ...
                Units=self.units, ...
                TimeUnits=self.time_units, ...
                StartDate=self.start_date, ...
                RmsXmin=self.rms_xmin, ...
                RmsXmax=self.rms_xmax, ...
                DispXmin=self.disp_xmin, ...
                DispXmax=self.disp_xmax, ...
                MakeSubplots=self.make_subplots, ...
                SingleLines=self.single_lines, ...
                ColorMap=self.color_map, ...
                UseMean=self.use_mean, ...
                PlotZero=self.plot_zero, ...
                ShowRms=self.show_rms, ...
                LegendLoc=self.legend_loc, ...
                ShowExtra=self.show_extra, ...
                SecondUnits=self.second_units, ...
                YLabel=self.ylabel, ...
                DataAsRows=self.data_as_rows, ...
                Tolerance=self.tolerance, ...
                UseZoh=self.use_zoh, ...
                LabelVertLines=self.label_vert_lines, ...
                FigVisible=self.fig_visible);
            self.verifyNotEmpty(self.fig_hand);
            self.verifyGreaterThanOrEqual(length(self.fig_hand), 1);
        end

        function test_none1(self)
            self.fig_hand = matspace.plotting.make_difference_plot(self.description, self.time_one, ...
                self.data_one, [], [], FigVisible=self.fig_visible);
            self.verifyNotEmpty(self.fig_hand);
            self.verifyGreaterThanOrEqual(length(self.fig_hand), 1);
        end

        function test_none2(self)
            self.fig_hand = matspace.plotting.make_difference_plot(self.description, [], [], self.time_two, ...
                self.data_two, FigVisible=self.fig_visible);
            self.verifyNotEmpty(self.fig_hand);
            self.verifyGreaterThanOrEqual(length(self.fig_hand), 1);
        end

        % @patch("lmspace.plotting.generic.logger")
        function test_none3(self)
            self.fig_hand = matspace.plotting.make_difference_plot('', [], [], [], [], FigVisible=self.fig_visible);
            % self.assertEqual(mock_logger.log.call_count, 1)
            % mock_logger.log.assert_called_with(
            %     LogLevel.L5, 'No %s data was provided, so no plot was generated for "%s".', "differences", ""
            % )
            self.verifyEmpty(self.fig_hand);
            self.assertEqual(length(self.fig_hand), 0);
        end
    end
end