classdef test_make_quaternion_plot < matlab.unittest.TestCase  %#ok<*PROP>

    % Tests the make_quaternion_plot function with the following cases:
    %     TBD

    properties
        fig_hand,
        description,
        time_one,
        quat_one,
        time_two,
        quat_two,
        name_one,
        name_two,
        time_units,
        start_date,
        plot_components,
        rms_xmin,
        rms_xmax,
        disp_xmin,
        disp_xmax,
        make_subplots,
        single_lines,
        use_mean,
        plot_zero,
        show_rms,
        legend_loc,
        show_extra,
        second_units,
        data_as_rows,
        extra_plotter,
        tolerance,
        use_zoh,
        label_vert_lines,
        fig_visible,
    end

    methods (TestMethodSetup)
        function initialize(self)
            self.fig_hand         = gobjects(1, 0);
            self.description      = 'example';
            self.time_one         = 0:10;
            self.quat_one         = matspace.quaternions.quat_norm(rand([4 11]));
            self.time_two         = 2:12;
            self.quat_two         = matspace.quaternions.quat_norm(rand([4 11]));
            self.name_one         = 'test1';
            self.name_two         = 'test2';
            self.time_units       = 'sec';
            self.start_date       = char(datetime('now'));
            self.plot_components  = true;
            self.rms_xmin         = 0;
            self.rms_xmax         = 10;
            self.disp_xmin        = -2;
            self.disp_xmax        = inf;
            self.make_subplots    = true;
            self.single_lines     = false;
            self.use_mean         = false;
            self.plot_zero        = false;
            self.show_rms         = true;
            self.legend_loc       = 'best';
            self.show_extra       = true;
            self.second_units     = {'µrad', 1e6};
            self.data_as_rows     = true;
            self.tolerance        = 0;
            self.use_zoh          = false;
            self.label_vert_lines = true;
            self.fig_visible      = false;
        end
    end

    methods (TestMethodTeardown)
        function closeFigure(self)
            close(self.fig_hand);
        end
    end

    methods (Test)
        function test_nominal(self)
            [self.fig_hand, err] = matspace.plotting.make_quaternion_plot(...
                self.description, ...
                self.time_one, ...
                self.quat_one, ...
                self.time_two, ...
                self.quat_two, ...
                NameOne=self.name_one, ...
                NameTwo=self.name_two, ...
                TimeUnits=self.time_units, ...
                StartDate=self.start_date, ...
                PlotComponents=self.plot_components, ...
                RmsXMin=self.rms_xmin, ...
                RmsXMax=self.rms_xmax, ...
                DispXMin=self.disp_xmin, ...
                DispXMax=self.disp_xmax, ...
                MakeSubplots=self.make_subplots, ...
                SingleLines=self.single_lines, ...
                UseMean=self.use_mean, ...
                PlotZero=self.plot_zero, ...
                ShowRms=self.show_rms, ...
                LegendLoc=self.legend_loc, ...
                ShowExtra=self.show_extra, ...
                DataAsRows=self.data_as_rows, ...
                Tolerance=self.tolerance, ...
                UseZoh=self.use_zoh, ...
                LabelVertLines=self.label_vert_lines, ...
                FigVisible=self.fig_visible);
            for i = 1:3
                self.verifyLessThan(abs(err.diff(i)), 3.15);
            end
        end

        function test_no_subplots(self)
            self.make_subplots = false;
            [self.fig_hand, err] = matspace.plotting.make_quaternion_plot(...
                self.description, ...
                self.time_one, ...
                self.quat_one, ...
                self.time_two, ...
                self.quat_two, ...
                NameOne=self.name_one, ...
                NameTwo=self.name_two, ...
                TimeUnits=self.time_units, ...
                StartDate=self.start_date, ...
                PlotComponents=self.plot_components, ...
                RmsXMin=self.rms_xmin, ...
                RmsXMax=self.rms_xmax, ...
                DispXMin=self.disp_xmin, ...
                DispXMax=self.disp_xmax, ...
                MakeSubplots=self.make_subplots, ...
                SingleLines=self.single_lines, ...
                UseMean=self.use_mean, ...
                PlotZero=self.plot_zero, ...
                ShowRms=self.show_rms, ...
                LegendLoc=self.legend_loc, ...
                ShowExtra=self.show_extra, ...
                DataAsRows=self.data_as_rows, ...
                Tolerance=self.tolerance, ...
                UseZoh=self.use_zoh, ...
                LabelVertLines=self.label_vert_lines, ...
                FigVisible=self.fig_visible);
            for i=1:3
                self.verifyLessThan(abs(err.diff(i)), 3.15);
            end
        end

        function test_no_components(self)
            self.plot_components = false;
            [self.fig_hand, err] = matspace.plotting.make_quaternion_plot(...
                self.description, ...
                self.time_one, ...
                self.quat_one, ...
                self.time_two, ...
                self.quat_two, ...
                NameOne=self.name_one, ...
                NameTwo=self.name_two, ...
                TimeUnits=self.time_units, ...
                StartDate=self.start_date, ...
                PlotComponents=self.plot_components, ...
                RmsXMin=self.rms_xmin, ...
                RmsXMax=self.rms_xmax, ...
                DispXMin=self.disp_xmin, ...
                DispXMax=self.disp_xmax, ...
                MakeSubplots=self.make_subplots, ...
                SingleLines=self.single_lines, ...
                UseMean=self.use_mean, ...
                PlotZero=self.plot_zero, ...
                ShowRms=self.show_rms, ...
                LegendLoc=self.legend_loc, ...
                ShowExtra=self.show_extra, ...
                DataAsRows=self.data_as_rows, ...
                Tolerance=self.tolerance, ...
                UseZoh=self.use_zoh, ...
                LabelVertLines=self.label_vert_lines, ...
                FigVisible=self.fig_visible);
            for i = 1:3
                self.verifyLessThan(abs(err.diff(i)), 3.15);
                self.verifyLessThan(abs(err.mag), 3.15);
            end
        end

        function test_no_start_date(self)
            self.start_date = '';
            [self.fig_hand, err] = matspace.plotting.make_quaternion_plot(...
                self.description, ...
                self.time_one, ...
                self.quat_one, ...
                self.time_two, ...
                self.quat_two, ...
                NameOne=self.name_one, ...
                NameTwo=self.name_two, ...
                TimeUnits=self.time_units, ...
                StartDate=self.start_date, ...
                PlotComponents=self.plot_components, ...
                RmsXMin=self.rms_xmin, ...
                RmsXMax=self.rms_xmax, ...
                DispXMin=self.disp_xmin, ...
                DispXMax=self.disp_xmax, ...
                MakeSubplots=self.make_subplots, ...
                SingleLines=self.single_lines, ...
                UseMean=self.use_mean, ...
                PlotZero=self.plot_zero, ...
                ShowRms=self.show_rms, ...
                LegendLoc=self.legend_loc, ...
                ShowExtra=self.show_extra, ...
                DataAsRows=self.data_as_rows, ...
                Tolerance=self.tolerance, ...
                UseZoh=self.use_zoh, ...
                LabelVertLines=self.label_vert_lines, ...
                FigVisible=self.fig_visible);
            for i = 1:3
                self.verifyLessThan(abs(err.diff(i)), 3.15);
            end
        end

        function test_only_quat_one(self)
            self.quat_two(:) = nan;
            self.name_two = '';
            [self.fig_hand, err] = matspace.plotting.make_quaternion_plot(...
                self.description, ...
                self.time_one, ...
                self.quat_one, ...
                self.time_two, ...
                self.quat_two, ...
                NameOne=self.name_one, ...
                NameTwo=self.name_two, ...
                TimeUnits=self.time_units, ...
                StartDate=self.start_date, ...
                PlotComponents=self.plot_components, ...
                RmsXMin=self.rms_xmin, ...
                RmsXMax=self.rms_xmax, ...
                DispXMin=self.disp_xmin, ...
                DispXMax=self.disp_xmax, ...
                MakeSubplots=self.make_subplots, ...
                SingleLines=self.single_lines, ...
                UseMean=self.use_mean, ...
                PlotZero=self.plot_zero, ...
                ShowRms=self.show_rms, ...
                LegendLoc=self.legend_loc, ...
                ShowExtra=self.show_extra, ...
                DataAsRows=self.data_as_rows, ...
                Tolerance=self.tolerance, ...
                UseZoh=self.use_zoh, ...
                LabelVertLines=self.label_vert_lines, ...
                FigVisible=self.fig_visible);
                self.verifyTrue(all(isnan(err.diff)));
        end

        function test_only_quat_two(self)
            self.name_one = '';
            [self.fig_hand, err] = matspace.plotting.make_quaternion_plot(...
                self.description, ...
                self.time_one, ...
                zeros(4, 0), ...
                self.time_two, ...
                self.quat_two, ...
                NameOne=self.name_one, ...
                NameTwo=self.name_two, ...
                TimeUnits=self.time_units, ...
                StartDate=self.start_date, ...
                PlotComponents=self.plot_components, ...
                RmsXMin=self.rms_xmin, ...
                RmsXMax=self.rms_xmax, ...
                DispXMin=self.disp_xmin, ...
                DispXMax=self.disp_xmax, ...
                MakeSubplots=self.make_subplots, ...
                SingleLines=self.single_lines, ...
                UseMean=self.use_mean, ...
                PlotZero=self.plot_zero, ...
                ShowRms=self.show_rms, ...
                LegendLoc=self.legend_loc, ...
                ShowExtra=self.show_extra, ...
                DataAsRows=self.data_as_rows, ...
                Tolerance=self.tolerance, ...
                UseZoh=self.use_zoh, ...
                LabelVertLines=self.label_vert_lines, ...
                FigVisible=self.fig_visible);
            self.verifyTrue(all(isnan(err.diff)));
        end

        function test_rms_bounds(self)
            self.rms_xmin = 5;
            self.rms_xmax = 7;
            [self.fig_hand, err] = matspace.plotting.make_quaternion_plot(...
                self.description, ...
                self.time_one, ...
                self.quat_one, ...
                self.time_two, ...
                self.quat_two, ...
                NameOne=self.name_one, ...
                NameTwo=self.name_two, ...
                TimeUnits=self.time_units, ...
                StartDate=self.start_date, ...
                PlotComponents=self.plot_components, ...
                RmsXMin=self.rms_xmin, ...
                RmsXMax=self.rms_xmax, ...
                DispXMin=self.disp_xmin, ...
                DispXMax=self.disp_xmax, ...
                MakeSubplots=self.make_subplots, ...
                SingleLines=self.single_lines, ...
                UseMean=self.use_mean, ...
                PlotZero=self.plot_zero, ...
                ShowRms=self.show_rms, ...
                LegendLoc=self.legend_loc, ...
                ShowExtra=self.show_extra, ...
                DataAsRows=self.data_as_rows, ...
                Tolerance=self.tolerance, ...
                UseZoh=self.use_zoh, ...
                LabelVertLines=self.label_vert_lines, ...
                FigVisible=self.fig_visible);
            for i = 1:3
                self.verifyLessThan(abs(err.diff(i)), 3.15);
            end
        end

        function test_use_mean(self)
            self.fig_hand = matspace.plotting.make_quaternion_plot(self.description, self.time_one, self.quat_one, ...
                self.time_two, self.quat_two, UseMean=true, FigVisible=self.fig_visible);
        end

        function test_no_rms_in_legend(self)
            self.fig_hand = matspace.plotting.make_quaternion_plot(self.description, self.time_one, self.quat_one, ...
                self.time_two, self.quat_two, UseMean=true, ShowRms=false, FigVisible=self.fig_visible);
        end

        function test_plot_zero(self)
            self.fig_hand = matspace.plotting.make_quaternion_plot(self.description, self.time_one, self.quat_one, ...
                self.time_two, self.quat_two, PlotZero=true, FigVisible=self.fig_visible);
        end

        function test_disp_bounds(self)
            self.fig_hand = matspace.plotting.make_quaternion_plot(self.description, self.time_one, self.quat_one, ...
                self.time_two, self.quat_two, DispXMin=2, DispXMax=5, FigVisible=self.fig_visible);
        end

        function test_no_overlap(self)
            time_one = 0:10;
            time_two = 2.5:12.5;
            self.fig_hand = matspace.plotting.make_quaternion_plot(self.description, time_one, self.quat_one, ...
                time_two, self.quat_two, FigVisible=self.fig_visible);
        end

        function test_none1(self)
            self.fig_hand = matspace.plotting.make_quaternion_plot(self.description, self.time_one, self.quat_one, ...
                zeros(1, 0), zeros(4, 0), FigVisible=self.fig_visible);
        end

        function test_none2(self)
            self.fig_hand = matspace.plotting.make_quaternion_plot(self.description, zeros(1, 0), zeros(4, 0), ...
                self.time_two, self.quat_two, FigVisible=self.fig_visible);
        end

        function test_none3(self)
            self.fig_hand = matspace.plotting.make_quaternion_plot('', zeros(1, 0), zeros(4, 0), ...
                zeros(1, 0), zeros(4, 0), FigVisible=self.fig_visible);
        end
    end
end