% Example to plot a PDF histogram with a CDF line overlaid.

description = 'Histogram';
data = abs(randn(1, 1000) / 3);
bins = 0:0.1:2;
if max(data) > 2
    bins = [bins, max(data) + 0.1];
end
cdf_x = 0.75;
cdf_y = 0.5;

% bins2 = [0.0, 0.1, 0.5, 1.0, 2.0, inf];

matspace.plotting.plot_histogram(...
    description, ...
    data, ...
    bins, ...
    SkipSetupPlots=true, ...
    ShowCdf=true, ...
    CdfX=cdf_x, ...
    CdfY=cdf_y, ...
    CdfRoundToBin=false, ...
    NormalizeSpacing=false);
