name: Run Unit Tests via runtests

on: [push]

jobs:
  run_tests:
    name: Run MATLAB Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v2

    - name: Run tests
      uses: matlab-actions/run-tests@v2
      with:
        source-folder: ${{ github.workspace }}
        select-by-folder: tests
        test-results-pdf: test-results/results.pdf
        test-results-junit: test-results/results.xml
        code-coverage-cobertura: code-coverage/coverage.xml
        
    - name: Test results summary
      uses: test-summary/action@v2
      with:
        paths: test-results/results.xml
        output: test-summary.md
      if: always()

    - name: Upload test results artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/results.xml
      if: always()
        
    - name: Upload test summary artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-summary
        path: test-summary.md
      if: always()

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-results
        path: code-coverage/coverage.xml
      if: always()

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: code-coverage/coverage.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '50 75'
      if: always()

    - name: Write test results to job summary
      run: cat test-summary.md >> $GITHUB_STEP_SUMMARY
      if: always()

    - name: Write code coverage results to job summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      if: always()
