name: Run Unit Tests via runtests

on: [push]

jobs:
  run_tests:
    name: Run MATLAB Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v2
    - name: Run tests
      uses: matlab-actions/run-tests@v2
      with:
        source-folder: ${{ github.workspace }}
        select-by-folder: tests
        test-results-pdf: test-results/results.pdf
        test-results-junit: test-results/results.xml
        code-coverage-cobertura: code-coverage/coverage.xml
