name: Run Unit Tests via runtests

on: [push]

jobs:
  run_tests:
    name: Run MATLAB Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v2
    - name: Run tests
      uses: matlab-actions/run-tests@v2
      with:
        source-folder: ${{ github.workspace }}
        select-by-folder: tests
        test-results-pdf: test-results/results.pdf
        test-results-junit: test-results/results.xml
        code-coverage-cobertura: code-coverage/coverage.xml
    - name: Upload results artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/results.xml
    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-results
        path: code-coverage/coverage.xml